/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelecionarEmpresaRouteImport } from './routes/selecionar-empresa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WSlugRouteImport } from './routes/w.$slug'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as WSlugIndexRouteImport } from './routes/w.$slug.index'
import { Route as WSlugPainelRouteImport } from './routes/w.$slug.painel'
import { Route as WSlugChamadosRouteImport } from './routes/w.$slug.chamados'
import { Route as WSlugChamadosIndexRouteImport } from './routes/w.$slug.chamados.index'
import { Route as WSlugChamadosQuadroRouteImport } from './routes/w.$slug.chamados.quadro'
import { Route as WSlugChamadosNovoRouteImport } from './routes/w.$slug.chamados.novo'
import { Route as WSlugChamadosNumeroRouteImport } from './routes/w.$slug.chamados.$numero'

const SelecionarEmpresaRoute = SelecionarEmpresaRouteImport.update({
  id: '/selecionar-empresa',
  path: '/selecionar-empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugRoute = WSlugRouteImport.update({
  id: '/w/$slug',
  path: '/w/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugIndexRoute = WSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugPainelRoute = WSlugPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugChamadosRoute = WSlugChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugChamadosIndexRoute = WSlugChamadosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WSlugChamadosRoute,
} as any)
const WSlugChamadosQuadroRoute = WSlugChamadosQuadroRouteImport.update({
  id: '/quadro',
  path: '/quadro',
  getParentRoute: () => WSlugChamadosRoute,
} as any)
const WSlugChamadosNovoRoute = WSlugChamadosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => WSlugChamadosRoute,
} as any)
const WSlugChamadosNumeroRoute = WSlugChamadosNumeroRouteImport.update({
  id: '/$numero',
  path: '/$numero',
  getParentRoute: () => WSlugChamadosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/selecionar-empresa': typeof SelecionarEmpresaRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/w/$slug/chamados': typeof WSlugChamadosRouteWithChildren
  '/w/$slug/painel': typeof WSlugPainelRoute
  '/w/$slug/': typeof WSlugIndexRoute
  '/w/$slug/chamados/$numero': typeof WSlugChamadosNumeroRoute
  '/w/$slug/chamados/novo': typeof WSlugChamadosNovoRoute
  '/w/$slug/chamados/quadro': typeof WSlugChamadosQuadroRoute
  '/w/$slug/chamados/': typeof WSlugChamadosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/selecionar-empresa': typeof SelecionarEmpresaRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/w/$slug/painel': typeof WSlugPainelRoute
  '/w/$slug': typeof WSlugIndexRoute
  '/w/$slug/chamados/$numero': typeof WSlugChamadosNumeroRoute
  '/w/$slug/chamados/novo': typeof WSlugChamadosNovoRoute
  '/w/$slug/chamados/quadro': typeof WSlugChamadosQuadroRoute
  '/w/$slug/chamados': typeof WSlugChamadosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/selecionar-empresa': typeof SelecionarEmpresaRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/w/$slug/chamados': typeof WSlugChamadosRouteWithChildren
  '/w/$slug/painel': typeof WSlugPainelRoute
  '/w/$slug/': typeof WSlugIndexRoute
  '/w/$slug/chamados/$numero': typeof WSlugChamadosNumeroRoute
  '/w/$slug/chamados/novo': typeof WSlugChamadosNovoRoute
  '/w/$slug/chamados/quadro': typeof WSlugChamadosQuadroRoute
  '/w/$slug/chamados/': typeof WSlugChamadosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/selecionar-empresa'
    | '/convite/$token'
    | '/w/$slug'
    | '/w/$slug/chamados'
    | '/w/$slug/painel'
    | '/w/$slug/'
    | '/w/$slug/chamados/$numero'
    | '/w/$slug/chamados/novo'
    | '/w/$slug/chamados/quadro'
    | '/w/$slug/chamados/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/selecionar-empresa'
    | '/convite/$token'
    | '/w/$slug/painel'
    | '/w/$slug'
    | '/w/$slug/chamados/$numero'
    | '/w/$slug/chamados/novo'
    | '/w/$slug/chamados/quadro'
    | '/w/$slug/chamados'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/selecionar-empresa'
    | '/convite/$token'
    | '/w/$slug'
    | '/w/$slug/chamados'
    | '/w/$slug/painel'
    | '/w/$slug/'
    | '/w/$slug/chamados/$numero'
    | '/w/$slug/chamados/novo'
    | '/w/$slug/chamados/quadro'
    | '/w/$slug/chamados/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SelecionarEmpresaRoute: typeof SelecionarEmpresaRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  WSlugRoute: typeof WSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/selecionar-empresa': {
      id: '/selecionar-empresa'
      path: '/selecionar-empresa'
      fullPath: '/selecionar-empresa'
      preLoaderRoute: typeof SelecionarEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug': {
      id: '/w/$slug'
      path: '/w/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof WSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug/': {
      id: '/w/$slug/'
      path: '/'
      fullPath: '/w/$slug/'
      preLoaderRoute: typeof WSlugIndexRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/painel': {
      id: '/w/$slug/painel'
      path: '/painel'
      fullPath: '/w/$slug/painel'
      preLoaderRoute: typeof WSlugPainelRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/chamados': {
      id: '/w/$slug/chamados'
      path: '/chamados'
      fullPath: '/w/$slug/chamados'
      preLoaderRoute: typeof WSlugChamadosRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/chamados/': {
      id: '/w/$slug/chamados/'
      path: '/'
      fullPath: '/w/$slug/chamados/'
      preLoaderRoute: typeof WSlugChamadosIndexRouteImport
      parentRoute: typeof WSlugChamadosRoute
    }
    '/w/$slug/chamados/quadro': {
      id: '/w/$slug/chamados/quadro'
      path: '/quadro'
      fullPath: '/w/$slug/chamados/quadro'
      preLoaderRoute: typeof WSlugChamadosQuadroRouteImport
      parentRoute: typeof WSlugChamadosRoute
    }
    '/w/$slug/chamados/novo': {
      id: '/w/$slug/chamados/novo'
      path: '/novo'
      fullPath: '/w/$slug/chamados/novo'
      preLoaderRoute: typeof WSlugChamadosNovoRouteImport
      parentRoute: typeof WSlugChamadosRoute
    }
    '/w/$slug/chamados/$numero': {
      id: '/w/$slug/chamados/$numero'
      path: '/$numero'
      fullPath: '/w/$slug/chamados/$numero'
      preLoaderRoute: typeof WSlugChamadosNumeroRouteImport
      parentRoute: typeof WSlugChamadosRoute
    }
  }
}

interface WSlugChamadosRouteChildren {
  WSlugChamadosNumeroRoute: typeof WSlugChamadosNumeroRoute
  WSlugChamadosNovoRoute: typeof WSlugChamadosNovoRoute
  WSlugChamadosQuadroRoute: typeof WSlugChamadosQuadroRoute
  WSlugChamadosIndexRoute: typeof WSlugChamadosIndexRoute
}

const WSlugChamadosRouteChildren: WSlugChamadosRouteChildren = {
  WSlugChamadosNumeroRoute: WSlugChamadosNumeroRoute,
  WSlugChamadosNovoRoute: WSlugChamadosNovoRoute,
  WSlugChamadosQuadroRoute: WSlugChamadosQuadroRoute,
  WSlugChamadosIndexRoute: WSlugChamadosIndexRoute,
}

const WSlugChamadosRouteWithChildren = WSlugChamadosRoute._addFileChildren(
  WSlugChamadosRouteChildren,
)

interface WSlugRouteChildren {
  WSlugChamadosRoute: typeof WSlugChamadosRouteWithChildren
  WSlugPainelRoute: typeof WSlugPainelRoute
  WSlugIndexRoute: typeof WSlugIndexRoute
}

const WSlugRouteChildren: WSlugRouteChildren = {
  WSlugChamadosRoute: WSlugChamadosRouteWithChildren,
  WSlugPainelRoute: WSlugPainelRoute,
  WSlugIndexRoute: WSlugIndexRoute,
}

const WSlugRouteWithChildren = WSlugRoute._addFileChildren(WSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SelecionarEmpresaRoute: SelecionarEmpresaRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  WSlugRoute: WSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
