/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelecionarEmpresaRouteImport } from './routes/selecionar-empresa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WSlugRouteImport } from './routes/w.$slug'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as WSlugIndexRouteImport } from './routes/w.$slug.index'
import { Route as WSlugProjetosRouteImport } from './routes/w.$slug.projetos'
import { Route as WSlugPainelRouteImport } from './routes/w.$slug.painel'
import { Route as WSlugInauguracoesRouteImport } from './routes/w.$slug.inauguracoes'
import { Route as WSlugConfiguracoesRouteImport } from './routes/w.$slug.configuracoes'
import { Route as WSlugChecklistsRouteImport } from './routes/w.$slug.checklists'
import { Route as WSlugChamadosRouteImport } from './routes/w.$slug.chamados'
import { Route as ApiPublicWhatsappNotifyRouteImport } from './routes/api/public/whatsapp-notify'
import { Route as WSlugProjetosIndexRouteImport } from './routes/w.$slug.projetos.index'
import { Route as WSlugChecklistsIndexRouteImport } from './routes/w.$slug.checklists.index'
import { Route as WSlugChamadosIndexRouteImport } from './routes/w.$slug.chamados.index'
import { Route as WSlugProjetosProjetoIdRouteImport } from './routes/w.$slug.projetos.$projetoId'
import { Route as WSlugMembrosUsuarioIdRouteImport } from './routes/w.$slug.membros.$usuarioId'
import { Route as WSlugChecklistsTemplateRouteImport } from './routes/w.$slug.checklists.template'
import { Route as WSlugChecklistsChecklistIdRouteImport } from './routes/w.$slug.checklists.$checklistId'
import { Route as WSlugChamadosQuadroRouteImport } from './routes/w.$slug.chamados.quadro'
import { Route as WSlugChamadosNovoRouteImport } from './routes/w.$slug.chamados.novo'
import { Route as WSlugChamadosNumeroRouteImport } from './routes/w.$slug.chamados.$numero'

const SelecionarEmpresaRoute = SelecionarEmpresaRouteImport.update({
  id: '/selecionar-empresa',
  path: '/selecionar-empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugRoute = WSlugRouteImport.update({
  id: '/w/$slug',
  path: '/w/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugIndexRoute = WSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugProjetosRoute = WSlugProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugPainelRoute = WSlugPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugInauguracoesRoute = WSlugInauguracoesRouteImport.update({
  id: '/inauguracoes',
  path: '/inauguracoes',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugConfiguracoesRoute = WSlugConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugChecklistsRoute = WSlugChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugChamadosRoute = WSlugChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => WSlugRoute,
} as any)
const ApiPublicWhatsappNotifyRoute = ApiPublicWhatsappNotifyRouteImport.update({
  id: '/api/public/whatsapp-notify',
  path: '/api/public/whatsapp-notify',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugProjetosIndexRoute = WSlugProjetosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WSlugProjetosRoute,
} as any)
const WSlugChecklistsIndexRoute = WSlugChecklistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WSlugChecklistsRoute,
} as any)
const WSlugChamadosIndexRoute = WSlugChamadosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WSlugChamadosRoute,
} as any)
const WSlugProjetosProjetoIdRoute = WSlugProjetosProjetoIdRouteImport.update({
  id: '/$projetoId',
  path: '/$projetoId',
  getParentRoute: () => WSlugProjetosRoute,
} as any)
const WSlugMembrosUsuarioIdRoute = WSlugMembrosUsuarioIdRouteImport.update({
  id: '/membros/$usuarioId',
  path: '/membros/$usuarioId',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugChecklistsTemplateRoute = WSlugChecklistsTemplateRouteImport.update({
  id: '/template',
  path: '/template',
  getParentRoute: () => WSlugChecklistsRoute,
} as any)
const WSlugChecklistsChecklistIdRoute =
  WSlugChecklistsChecklistIdRouteImport.update({
    id: '/$checklistId',
    path: '/$checklistId',
    getParentRoute: () => WSlugChecklistsRoute,
  } as any)
const WSlugChamadosQuadroRoute = WSlugChamadosQuadroRouteImport.update({
  id: '/quadro',
  path: '/quadro',
  getParentRoute: () => WSlugChamadosRoute,
} as any)
const WSlugChamadosNovoRoute = WSlugChamadosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => WSlugChamadosRoute,
} as any)
const WSlugChamadosNumeroRoute = WSlugChamadosNumeroRouteImport.update({
  id: '/$numero',
  path: '/$numero',
  getParentRoute: () => WSlugChamadosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/selecionar-empresa': typeof SelecionarEmpresaRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/api/public/whatsapp-notify': typeof ApiPublicWhatsappNotifyRoute
  '/w/$slug/chamados': typeof WSlugChamadosRouteWithChildren
  '/w/$slug/checklists': typeof WSlugChecklistsRouteWithChildren
  '/w/$slug/configuracoes': typeof WSlugConfiguracoesRoute
  '/w/$slug/inauguracoes': typeof WSlugInauguracoesRoute
  '/w/$slug/painel': typeof WSlugPainelRoute
  '/w/$slug/projetos': typeof WSlugProjetosRouteWithChildren
  '/w/$slug/': typeof WSlugIndexRoute
  '/w/$slug/chamados/$numero': typeof WSlugChamadosNumeroRoute
  '/w/$slug/chamados/novo': typeof WSlugChamadosNovoRoute
  '/w/$slug/chamados/quadro': typeof WSlugChamadosQuadroRoute
  '/w/$slug/checklists/$checklistId': typeof WSlugChecklistsChecklistIdRoute
  '/w/$slug/checklists/template': typeof WSlugChecklistsTemplateRoute
  '/w/$slug/membros/$usuarioId': typeof WSlugMembrosUsuarioIdRoute
  '/w/$slug/projetos/$projetoId': typeof WSlugProjetosProjetoIdRoute
  '/w/$slug/chamados/': typeof WSlugChamadosIndexRoute
  '/w/$slug/checklists/': typeof WSlugChecklistsIndexRoute
  '/w/$slug/projetos/': typeof WSlugProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/selecionar-empresa': typeof SelecionarEmpresaRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/api/public/whatsapp-notify': typeof ApiPublicWhatsappNotifyRoute
  '/w/$slug/configuracoes': typeof WSlugConfiguracoesRoute
  '/w/$slug/inauguracoes': typeof WSlugInauguracoesRoute
  '/w/$slug/painel': typeof WSlugPainelRoute
  '/w/$slug': typeof WSlugIndexRoute
  '/w/$slug/chamados/$numero': typeof WSlugChamadosNumeroRoute
  '/w/$slug/chamados/novo': typeof WSlugChamadosNovoRoute
  '/w/$slug/chamados/quadro': typeof WSlugChamadosQuadroRoute
  '/w/$slug/checklists/$checklistId': typeof WSlugChecklistsChecklistIdRoute
  '/w/$slug/checklists/template': typeof WSlugChecklistsTemplateRoute
  '/w/$slug/membros/$usuarioId': typeof WSlugMembrosUsuarioIdRoute
  '/w/$slug/projetos/$projetoId': typeof WSlugProjetosProjetoIdRoute
  '/w/$slug/chamados': typeof WSlugChamadosIndexRoute
  '/w/$slug/checklists': typeof WSlugChecklistsIndexRoute
  '/w/$slug/projetos': typeof WSlugProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/selecionar-empresa': typeof SelecionarEmpresaRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/api/public/whatsapp-notify': typeof ApiPublicWhatsappNotifyRoute
  '/w/$slug/chamados': typeof WSlugChamadosRouteWithChildren
  '/w/$slug/checklists': typeof WSlugChecklistsRouteWithChildren
  '/w/$slug/configuracoes': typeof WSlugConfiguracoesRoute
  '/w/$slug/inauguracoes': typeof WSlugInauguracoesRoute
  '/w/$slug/painel': typeof WSlugPainelRoute
  '/w/$slug/projetos': typeof WSlugProjetosRouteWithChildren
  '/w/$slug/': typeof WSlugIndexRoute
  '/w/$slug/chamados/$numero': typeof WSlugChamadosNumeroRoute
  '/w/$slug/chamados/novo': typeof WSlugChamadosNovoRoute
  '/w/$slug/chamados/quadro': typeof WSlugChamadosQuadroRoute
  '/w/$slug/checklists/$checklistId': typeof WSlugChecklistsChecklistIdRoute
  '/w/$slug/checklists/template': typeof WSlugChecklistsTemplateRoute
  '/w/$slug/membros/$usuarioId': typeof WSlugMembrosUsuarioIdRoute
  '/w/$slug/projetos/$projetoId': typeof WSlugProjetosProjetoIdRoute
  '/w/$slug/chamados/': typeof WSlugChamadosIndexRoute
  '/w/$slug/checklists/': typeof WSlugChecklistsIndexRoute
  '/w/$slug/projetos/': typeof WSlugProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/selecionar-empresa'
    | '/convite/$token'
    | '/w/$slug'
    | '/api/public/whatsapp-notify'
    | '/w/$slug/chamados'
    | '/w/$slug/checklists'
    | '/w/$slug/configuracoes'
    | '/w/$slug/inauguracoes'
    | '/w/$slug/painel'
    | '/w/$slug/projetos'
    | '/w/$slug/'
    | '/w/$slug/chamados/$numero'
    | '/w/$slug/chamados/novo'
    | '/w/$slug/chamados/quadro'
    | '/w/$slug/checklists/$checklistId'
    | '/w/$slug/checklists/template'
    | '/w/$slug/membros/$usuarioId'
    | '/w/$slug/projetos/$projetoId'
    | '/w/$slug/chamados/'
    | '/w/$slug/checklists/'
    | '/w/$slug/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/selecionar-empresa'
    | '/convite/$token'
    | '/api/public/whatsapp-notify'
    | '/w/$slug/configuracoes'
    | '/w/$slug/inauguracoes'
    | '/w/$slug/painel'
    | '/w/$slug'
    | '/w/$slug/chamados/$numero'
    | '/w/$slug/chamados/novo'
    | '/w/$slug/chamados/quadro'
    | '/w/$slug/checklists/$checklistId'
    | '/w/$slug/checklists/template'
    | '/w/$slug/membros/$usuarioId'
    | '/w/$slug/projetos/$projetoId'
    | '/w/$slug/chamados'
    | '/w/$slug/checklists'
    | '/w/$slug/projetos'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/selecionar-empresa'
    | '/convite/$token'
    | '/w/$slug'
    | '/api/public/whatsapp-notify'
    | '/w/$slug/chamados'
    | '/w/$slug/checklists'
    | '/w/$slug/configuracoes'
    | '/w/$slug/inauguracoes'
    | '/w/$slug/painel'
    | '/w/$slug/projetos'
    | '/w/$slug/'
    | '/w/$slug/chamados/$numero'
    | '/w/$slug/chamados/novo'
    | '/w/$slug/chamados/quadro'
    | '/w/$slug/checklists/$checklistId'
    | '/w/$slug/checklists/template'
    | '/w/$slug/membros/$usuarioId'
    | '/w/$slug/projetos/$projetoId'
    | '/w/$slug/chamados/'
    | '/w/$slug/checklists/'
    | '/w/$slug/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SelecionarEmpresaRoute: typeof SelecionarEmpresaRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  WSlugRoute: typeof WSlugRouteWithChildren
  ApiPublicWhatsappNotifyRoute: typeof ApiPublicWhatsappNotifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/selecionar-empresa': {
      id: '/selecionar-empresa'
      path: '/selecionar-empresa'
      fullPath: '/selecionar-empresa'
      preLoaderRoute: typeof SelecionarEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug': {
      id: '/w/$slug'
      path: '/w/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof WSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug/': {
      id: '/w/$slug/'
      path: '/'
      fullPath: '/w/$slug/'
      preLoaderRoute: typeof WSlugIndexRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/projetos': {
      id: '/w/$slug/projetos'
      path: '/projetos'
      fullPath: '/w/$slug/projetos'
      preLoaderRoute: typeof WSlugProjetosRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/painel': {
      id: '/w/$slug/painel'
      path: '/painel'
      fullPath: '/w/$slug/painel'
      preLoaderRoute: typeof WSlugPainelRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/inauguracoes': {
      id: '/w/$slug/inauguracoes'
      path: '/inauguracoes'
      fullPath: '/w/$slug/inauguracoes'
      preLoaderRoute: typeof WSlugInauguracoesRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/configuracoes': {
      id: '/w/$slug/configuracoes'
      path: '/configuracoes'
      fullPath: '/w/$slug/configuracoes'
      preLoaderRoute: typeof WSlugConfiguracoesRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/checklists': {
      id: '/w/$slug/checklists'
      path: '/checklists'
      fullPath: '/w/$slug/checklists'
      preLoaderRoute: typeof WSlugChecklistsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/chamados': {
      id: '/w/$slug/chamados'
      path: '/chamados'
      fullPath: '/w/$slug/chamados'
      preLoaderRoute: typeof WSlugChamadosRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/api/public/whatsapp-notify': {
      id: '/api/public/whatsapp-notify'
      path: '/api/public/whatsapp-notify'
      fullPath: '/api/public/whatsapp-notify'
      preLoaderRoute: typeof ApiPublicWhatsappNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug/projetos/': {
      id: '/w/$slug/projetos/'
      path: '/'
      fullPath: '/w/$slug/projetos/'
      preLoaderRoute: typeof WSlugProjetosIndexRouteImport
      parentRoute: typeof WSlugProjetosRoute
    }
    '/w/$slug/checklists/': {
      id: '/w/$slug/checklists/'
      path: '/'
      fullPath: '/w/$slug/checklists/'
      preLoaderRoute: typeof WSlugChecklistsIndexRouteImport
      parentRoute: typeof WSlugChecklistsRoute
    }
    '/w/$slug/chamados/': {
      id: '/w/$slug/chamados/'
      path: '/'
      fullPath: '/w/$slug/chamados/'
      preLoaderRoute: typeof WSlugChamadosIndexRouteImport
      parentRoute: typeof WSlugChamadosRoute
    }
    '/w/$slug/projetos/$projetoId': {
      id: '/w/$slug/projetos/$projetoId'
      path: '/$projetoId'
      fullPath: '/w/$slug/projetos/$projetoId'
      preLoaderRoute: typeof WSlugProjetosProjetoIdRouteImport
      parentRoute: typeof WSlugProjetosRoute
    }
    '/w/$slug/membros/$usuarioId': {
      id: '/w/$slug/membros/$usuarioId'
      path: '/membros/$usuarioId'
      fullPath: '/w/$slug/membros/$usuarioId'
      preLoaderRoute: typeof WSlugMembrosUsuarioIdRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/checklists/template': {
      id: '/w/$slug/checklists/template'
      path: '/template'
      fullPath: '/w/$slug/checklists/template'
      preLoaderRoute: typeof WSlugChecklistsTemplateRouteImport
      parentRoute: typeof WSlugChecklistsRoute
    }
    '/w/$slug/checklists/$checklistId': {
      id: '/w/$slug/checklists/$checklistId'
      path: '/$checklistId'
      fullPath: '/w/$slug/checklists/$checklistId'
      preLoaderRoute: typeof WSlugChecklistsChecklistIdRouteImport
      parentRoute: typeof WSlugChecklistsRoute
    }
    '/w/$slug/chamados/quadro': {
      id: '/w/$slug/chamados/quadro'
      path: '/quadro'
      fullPath: '/w/$slug/chamados/quadro'
      preLoaderRoute: typeof WSlugChamadosQuadroRouteImport
      parentRoute: typeof WSlugChamadosRoute
    }
    '/w/$slug/chamados/novo': {
      id: '/w/$slug/chamados/novo'
      path: '/novo'
      fullPath: '/w/$slug/chamados/novo'
      preLoaderRoute: typeof WSlugChamadosNovoRouteImport
      parentRoute: typeof WSlugChamadosRoute
    }
    '/w/$slug/chamados/$numero': {
      id: '/w/$slug/chamados/$numero'
      path: '/$numero'
      fullPath: '/w/$slug/chamados/$numero'
      preLoaderRoute: typeof WSlugChamadosNumeroRouteImport
      parentRoute: typeof WSlugChamadosRoute
    }
  }
}

interface WSlugChamadosRouteChildren {
  WSlugChamadosNumeroRoute: typeof WSlugChamadosNumeroRoute
  WSlugChamadosNovoRoute: typeof WSlugChamadosNovoRoute
  WSlugChamadosQuadroRoute: typeof WSlugChamadosQuadroRoute
  WSlugChamadosIndexRoute: typeof WSlugChamadosIndexRoute
}

const WSlugChamadosRouteChildren: WSlugChamadosRouteChildren = {
  WSlugChamadosNumeroRoute: WSlugChamadosNumeroRoute,
  WSlugChamadosNovoRoute: WSlugChamadosNovoRoute,
  WSlugChamadosQuadroRoute: WSlugChamadosQuadroRoute,
  WSlugChamadosIndexRoute: WSlugChamadosIndexRoute,
}

const WSlugChamadosRouteWithChildren = WSlugChamadosRoute._addFileChildren(
  WSlugChamadosRouteChildren,
)

interface WSlugChecklistsRouteChildren {
  WSlugChecklistsChecklistIdRoute: typeof WSlugChecklistsChecklistIdRoute
  WSlugChecklistsTemplateRoute: typeof WSlugChecklistsTemplateRoute
  WSlugChecklistsIndexRoute: typeof WSlugChecklistsIndexRoute
}

const WSlugChecklistsRouteChildren: WSlugChecklistsRouteChildren = {
  WSlugChecklistsChecklistIdRoute: WSlugChecklistsChecklistIdRoute,
  WSlugChecklistsTemplateRoute: WSlugChecklistsTemplateRoute,
  WSlugChecklistsIndexRoute: WSlugChecklistsIndexRoute,
}

const WSlugChecklistsRouteWithChildren = WSlugChecklistsRoute._addFileChildren(
  WSlugChecklistsRouteChildren,
)

interface WSlugProjetosRouteChildren {
  WSlugProjetosProjetoIdRoute: typeof WSlugProjetosProjetoIdRoute
  WSlugProjetosIndexRoute: typeof WSlugProjetosIndexRoute
}

const WSlugProjetosRouteChildren: WSlugProjetosRouteChildren = {
  WSlugProjetosProjetoIdRoute: WSlugProjetosProjetoIdRoute,
  WSlugProjetosIndexRoute: WSlugProjetosIndexRoute,
}

const WSlugProjetosRouteWithChildren = WSlugProjetosRoute._addFileChildren(
  WSlugProjetosRouteChildren,
)

interface WSlugRouteChildren {
  WSlugChamadosRoute: typeof WSlugChamadosRouteWithChildren
  WSlugChecklistsRoute: typeof WSlugChecklistsRouteWithChildren
  WSlugConfiguracoesRoute: typeof WSlugConfiguracoesRoute
  WSlugInauguracoesRoute: typeof WSlugInauguracoesRoute
  WSlugPainelRoute: typeof WSlugPainelRoute
  WSlugProjetosRoute: typeof WSlugProjetosRouteWithChildren
  WSlugIndexRoute: typeof WSlugIndexRoute
  WSlugMembrosUsuarioIdRoute: typeof WSlugMembrosUsuarioIdRoute
}

const WSlugRouteChildren: WSlugRouteChildren = {
  WSlugChamadosRoute: WSlugChamadosRouteWithChildren,
  WSlugChecklistsRoute: WSlugChecklistsRouteWithChildren,
  WSlugConfiguracoesRoute: WSlugConfiguracoesRoute,
  WSlugInauguracoesRoute: WSlugInauguracoesRoute,
  WSlugPainelRoute: WSlugPainelRoute,
  WSlugProjetosRoute: WSlugProjetosRouteWithChildren,
  WSlugIndexRoute: WSlugIndexRoute,
  WSlugMembrosUsuarioIdRoute: WSlugMembrosUsuarioIdRoute,
}

const WSlugRouteWithChildren = WSlugRoute._addFileChildren(WSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SelecionarEmpresaRoute: SelecionarEmpresaRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  WSlugRoute: WSlugRouteWithChildren,
  ApiPublicWhatsappNotifyRoute: ApiPublicWhatsappNotifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
